### ISSUE TITLE
Merge check hook

### ISSUE THREAD

**Issue by henriklynggaard** [ngsru/atlassian-external-hooks#18]
Support for merge check hook would be created so I can avoid writing java for performing simple merge checks script

https://developer.atlassian.com/stash/docs/latest/tutorials-and-examples/controlling-when-pull-requests-can-be-merged.html

Please add some caching functionality as my scripts take a while

**Comment by andreineculau** [comment]
+1

**Comment by greened** [comment]
+10

We could really use this.

**Comment by greened** [comment]
See PR #32.

**Comment by greened** [comment]
There is a LOT of information in a pull request that a Merge Check hook could potentially examine.  I started by simply passing the From Repository, From Commit ID, To Repository and To Commit ID to the hook along with the standard environment variables the other hooks use.  That should be sufficient to extract a bunch of other information but it's easy enough to pass more if needed.  I only needed to look at the actual commits being merged so that's all I did so far.
